# Generated by Django 4.2.1 on 2023-06-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=300)),
                ('product_category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminside.vendordetails')),
            ],
        ),
    ]
