# Generated by Django 4.2.1 on 2023-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='product/images'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='product/images'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='product/images'),
        ),
    ]
