# Generated by Django 4.2.1 on 2023-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0002_productdetails_img2_productdetails_img3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='vendor',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='vendor_id',
            field=models.IntegerField(default=0),
        ),
    ]
