# Generated by Django 4.2.1 on 2023-06-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0003_remove_productdetails_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
