# Generated by Django 4.2.1 on 2023-06-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0004_productdetails_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('address_id', models.IntegerField()),
                ('vendor_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=100)),
                ('date_and_time', models.DateTimeField()),
            ],
        ),
    ]
