# Generated by Django 4.2.1 on 2023-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0005_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
