# Generated by Django 4.2.1 on 2023-06-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0006_orderdetails_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='cost',
            new_name='amount',
        ),
    ]
