# Generated by Django 4.2.1 on 2023-06-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0007_rename_cost_orderdetails_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
