# Generated by Django 4.2.1 on 2023-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0010_alter_orderdetails_bunch_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='is_closed_order',
            field=models.BooleanField(default=False),
        ),
    ]
