# Generated by Django 4.2.1 on 2023-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0011_orderdetails_is_closed_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
