# Generated by Django 4.2.1 on 2023-06-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0013_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='PrePaidOrder',
        ),
    ]
