# Generated by Django 4.2.1 on 2023-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0015_remove_prepaidorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidorder',
            name='order',
            field=models.CharField(max_length=100),
        ),
    ]
