# Generated by Django 4.2.1 on 2023-06-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0016_alter_prepaidorder_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepaidorder',
            old_name='order',
            new_name='order_id',
        ),
    ]
