# Generated by Django 4.2.1 on 2023-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0018_alter_orderdetails_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('notification_content', models.CharField(max_length=300)),
                ('date_and_time', models.DateTimeField()),
            ],
        ),
    ]
