# Generated by Django 4.2.1 on 2023-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0019_vendornotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendornotification',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
