# Generated by Django 4.2.1 on 2023-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0020_vendornotification_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendornotification',
            name='notified',
            field=models.BooleanField(default=True),
        ),
    ]
