# Generated by Django 4.2.1 on 2023-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0021_vendornotification_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendornotification',
            name='notified',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='notified',
            field=models.BooleanField(default=True),
        ),
    ]
