# Generated by Django 4.2.1 on 2023-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0022_remove_vendornotification_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
