# Generated by Django 4.2.1 on 2023-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0023_alter_productdetails_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('coupon_code', models.CharField(max_length=100)),
                ('coupon_description', models.CharField(max_length=300)),
                ('coupon_type', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
