# Generated by Django 4.2.1 on 2023-06-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0024_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
