# Generated by Django 4.2.1 on 2023-06-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0025_coupon_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
