# Generated by Django 4.2.1 on 2023-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0026_productdetails_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='bunch_order_amount',
            field=models.IntegerField(default=0),
        ),
    ]
