# Generated by Django 4.2.1 on 2023-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0027_orderdetails_bunch_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='coupon',
            field=models.IntegerField(default=0),
        ),
    ]
