# Generated by Django 4.2.1 on 2023-06-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0028_orderdetails_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='coupon',
            new_name='coupon_id',
        ),
    ]
