# Generated by Django 4.2.1 on 2023-05-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
