# Generated by Django 4.2.1 on 2023-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_basket_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
