# Generated by Django 4.2.1 on 2023-06-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_basket_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
