# Generated by Django 4.2.1 on 2023-06-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0010_alter_basket_quantity_alter_basket_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total',
            field=models.IntegerField(),
        ),
    ]
