# Generated by Django 4.2.1 on 2023-06-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0011_alter_basket_quantity_alter_basket_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basket',
            name='unit_price',
            field=models.IntegerField(max_length=100),
        ),
    ]
