# Generated by Django 4.2.1 on 2023-06-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0012_alter_basket_quantity_alter_basket_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basket',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
