# Generated by Django 4.2.1 on 2023-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0013_alter_basket_quantity_alter_basket_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
