# Generated by Django 4.2.1 on 2023-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0016_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alt_phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
