# Generated by Django 4.2.1 on 2023-06-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0020_usercouponsapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercouponsapplied',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
