# Generated by Django 4.2.1 on 2023-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_vendordetails_license2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('vendor_id', models.IntegerField()),
                ('amount_received', models.FloatField()),
                ('platform_commision', models.FloatField()),
                ('vendor_rembursment', models.FloatField()),
            ],
        ),
    ]
