# Generated by Django 4.2.1 on 2023-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='order_closed_date',
            field=models.DateTimeField(default=None),
        ),
    ]
