# Generated by Django 4.2.1 on 2023-06-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_accounts_order_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='days_remaining_for_rembursment',
            field=models.IntegerField(default=None),
        ),
    ]
