# Generated by Django 4.2.1 on 2023-06-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_alter_accounts_days_remaining_for_rembursment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='order_rembursment_due_date',
            field=models.DateTimeField(default=None),
        ),
    ]
