# Generated by Django 4.2.1 on 2023-06-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_accounts_order_rembursment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='days_remaining_for_rembursment',
        ),
    ]
