# Generated by Django 4.2.1 on 2023-06-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_accounts_days_remaining_for_rembursment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='days_remaining_for_rembursment',
        ),
    ]
