# Generated by Django 4.2.1 on 2023-06-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_remove_sales_bunch_order_id_remove_sales_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product',
            new_name='product_name',
        ),
    ]
